plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - name: "@semantic-release/exec"
    publishCmd: "flutter build apk --target lib/app/app.dart"
  - "@semantic-release/git"
  - "@semantic-release/github"

branches:
  - main
  - dev