plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - name: "@semantic-release/exec"
    publishCmd: "flutter build apk --target lib/app/app.dart"
  - "@semantic-release/git"
  - name: "@semantic-release/github"
    assets:
      - path: "build/app/outputs/apk/release/app-release.apk"
        label: "APK"

branches:
  - main
  - dev