branches:
  - main
  - name: dev
    prerelease: true

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "semantic-release-pub"
    - publishPub: false
      updateBuildNumber: true
  - - "@semantic-release/exec"
    - prepareCmd: "flutter build apk --release --target lib/app/app.dart"
  - - "@semantic-release/github"
    - assets:
      - path: "build/app/outputs/apk/release/app-release.apk"
  - - "@semantic-release/git"
    - assets: ["pubspec.yaml"]
      message: "chore(release): ${nextRelease.version}"