name: Build for Android
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build apk --release --target lib\app\app.dart
    - run: flutter build appbundle --release --target lib\app\app.dart
    - name: Upload App
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: release-appbundle
        path: build/app/outputs/bundle/release/app-release.aab
