name: Build for Android
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get

    - name: Cache Gradle
      uses: burrunan/gradle-cache-action@v3
      with:
        build-root-directory: ${{ github.workspace }}/android

    - name: Setup keystore
      run: |
        cd android
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" > keystore.properties
        echo "password=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
        echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> keystore.properties
        base64 -d <<< "${{ secrets.KEYSTORE }}" > $RUNNER_TEMP/keystore.jks
        echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties
    
    - name: Generate files
      run: dart run build_runner build --delete-conflicting-outputs

    - run: flutter build apk --release --target lib/app/app.dart
    - run: flutter build appbundle --release --target lib/app/app.dart
    - name: Upload App
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: release-appbundle
        path: build/app/outputs/bundle/release/app-release.aab
