name: Release Android with Semantic Release

on:
  push:
    branches:
      - main
      - pre-release
      
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: 'npm'

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3
        with:
          build-root-directory: ${{ github.workspace }}/android

      - name: Install Dependencies (Node.js)
        run: npm i

      - name: Get Dependencies
        run: flutter pub get

      - name: Generate Files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Setup KeyStore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > "android/app/keystore.jks"

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v5
        id: semantic
        with:
          semantic_version: 24.2.9
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
